name: Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  demo:
    environment: testprod
    runs-on: ubuntu-latest
    steps:
      - run: echo "event ${{ github.event_name }} / repo ${{ github.repository }} / ref ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
