name: Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push, workflow_dispatch]
jobs:
  demo:
    environment: testprod
    runs-on: ubuntu-latest
    steps:
      - run: echo "event ${{ github.event_name }} / repo ${{ github.repository }} / ref ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.0
      - name: Check npm version
        run: |
          LAST_INVALID_VER="11.10.1"
          if [ $(npm -v) = $(printf "$LAST_INVALID_VER\n$(npm -v)" | sort -V | head -n1) ]; then
            echo "Error: Found npm@$(npm -v), which isn't support min-release-age"
            exit 1
          fi
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
